# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/rubyx/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),rubyx)

$(call add-radio-file-sha1-checked,radio/audio_dsp.img,2d526c634ebf59a59dffdf99c562e4390c94b2d9)
$(call add-radio-file-sha1-checked,radio/cam_vpu1.img,afd2a226e31837ec144db7023e35653135eec2dd)
$(call add-radio-file-sha1-checked,radio/cam_vpu2.img,689437d1b9caae756cb271951be44f77dea8a5e8)
$(call add-radio-file-sha1-checked,radio/cam_vpu3.img,5a830b34017db9fcb75894a3117e330f7680d209)
$(call add-radio-file-sha1-checked,radio/dpm.img,bd6932e7db499b5be931ada0c548fa852854b413)
$(call add-radio-file-sha1-checked,radio/gz.img,52f2ae88a338792bc6e688bb10ae3b26d0f5aab5)
$(call add-radio-file-sha1-checked,radio/lk.img,39c12d2727b35be8cedbe863063c85ba657478c6)
$(call add-radio-file-sha1-checked,radio/logo.img,325f780a93615207a617173294291ce28c7e74f2)
$(call add-radio-file-sha1-checked,radio/mcupm.img,bea5cf5f95d103d4738a417312273b87a648a5cc)
$(call add-radio-file-sha1-checked,radio/md1img.img,f5e397930304583017dab27e438350f82adcada7)
$(call add-radio-file-sha1-checked,radio/pi_img.img,1b186fc36edafa8fd3560d3f060e8968c48fd590)
$(call add-radio-file-sha1-checked,radio/preloader_raw.img,899f8be764be4ec1c1f2f27f567b16bdc9a3f04a)
$(call add-radio-file-sha1-checked,radio/scp.img,a94b996cb62a273f41339cff6f67d380a1b89589)
$(call add-radio-file-sha1-checked,radio/spmfw.img,6086ca2dcd24171e9658bc3a7cf2360b519834b8)
$(call add-radio-file-sha1-checked,radio/sspm.img,c2478911c41e425c56d4f04304896499a0cf479b)
$(call add-radio-file-sha1-checked,radio/tee.img,e68f5937266512decb2d87ff76b8d4a670972176)

endif
