# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/rubyx/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),rubyx)

$(call add-radio-file-sha1-checked,radio/audio_dsp.img,83415ca07c68c02e7952f6a4c7bd3f754ee6cf8d)
$(call add-radio-file-sha1-checked,radio/cam_vpu1.img,f99d208e4fdecbf718c9db9dff955ccf1a7baac3)
$(call add-radio-file-sha1-checked,radio/cam_vpu2.img,7df0c5b4f6cb599c3bdc279925bc0187fcc114d7)
$(call add-radio-file-sha1-checked,radio/cam_vpu3.img,c3937371c404cbe3dbfbdc029e2e84f96442e984)
$(call add-radio-file-sha1-checked,radio/dpm.img,ef1a2abe4d7d8e6542e11b8a0e17dc1e7369f29d)
$(call add-radio-file-sha1-checked,radio/gz.img,d5fb0234fe433255923068d653449569bee88f23)
$(call add-radio-file-sha1-checked,radio/lk.img,6fb1aef9a4cf282416e87262069a9a0613f38494)
$(call add-radio-file-sha1-checked,radio/logo.img,c2577192cbda7ccc596da42e5412b1b4a7b727c3)
$(call add-radio-file-sha1-checked,radio/mcupm.img,d903241ae310163e402927a065a8fc67d620e8db)
$(call add-radio-file-sha1-checked,radio/md1img.img,71487f032f1b9b212bd71f91ea320a12856bfb9f)
$(call add-radio-file-sha1-checked,radio/pi_img.img,a934e528310f343efcd37a1cb82dcd4e8669ecc3)
$(call add-radio-file-sha1-checked,radio/preloader_raw.img,5dc86b3b510803d20d7ac1272cea78174ce34dca)
$(call add-radio-file-sha1-checked,radio/scp.img,8f768387fa9c5f494d5c3fc1e6d283dd0148858f)
$(call add-radio-file-sha1-checked,radio/spmfw.img,cca594959599f5053d86063066e043cf062493a7)
$(call add-radio-file-sha1-checked,radio/sspm.img,1812b0e58e2a704592353fde2dc4ebdd814c5994)
$(call add-radio-file-sha1-checked,radio/tee.img,5cfcef2b9e49a4b9c30ee6d532bbb90fec620da9)

endif
