# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/rubyx/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),rubyx)

$(call add-radio-file-sha1-checked,radio/audio_dsp.img,f88addda8a6c7fe7980c770811bca692f1f2ad1e)
$(call add-radio-file-sha1-checked,radio/cam_vpu1.img,3f236eb4edf3cf6d090ae4782a4917c2020e8f6c)
$(call add-radio-file-sha1-checked,radio/cam_vpu2.img,f8ebf4e0194e4e41543218a69d1134a61388e13b)
$(call add-radio-file-sha1-checked,radio/cam_vpu3.img,9ca5fff8e66206d24c0b765e426c005a0d202393)
$(call add-radio-file-sha1-checked,radio/dpm.img,330d09e367b1860bbe35a831472ee7e38d40c81d)
$(call add-radio-file-sha1-checked,radio/gz.img,90a6147ab67401d5931daa7b5cf169cac005f7d6)
$(call add-radio-file-sha1-checked,radio/lk.img,3db532a27f7a8199e7e220bec1ca8b48f1d99781)
$(call add-radio-file-sha1-checked,radio/logo.img,971d3c96c765ff83afaae50c7600a91904b22d3d)
$(call add-radio-file-sha1-checked,radio/mcupm.img,0dbee7f5b36b290c07992e569ef3e911d938f790)
$(call add-radio-file-sha1-checked,radio/md1img.img,791650a18de47627d5644ccab9a67914fdafc8b5)
$(call add-radio-file-sha1-checked,radio/pi_img.img,916cc2a093ba4297ba1ec99a1263ae3c1ee73925)
$(call add-radio-file-sha1-checked,radio/preloader_raw.img,e536c934a0aed6aaaac226faa9e2b65a9a9aaf1c)
$(call add-radio-file-sha1-checked,radio/scp.img,f869f220ada6c2f3149abfca15e27668f7cd565d)
$(call add-radio-file-sha1-checked,radio/spmfw.img,ad65dc5eb1643d7ee6da68c9b37f72bd205a5ab5)
$(call add-radio-file-sha1-checked,radio/sspm.img,f5be422c4381d6a3a15af853b6276e7403d8cf13)
$(call add-radio-file-sha1-checked,radio/tee.img,4e30c9da4908d8304fee8399c48a43d15f469382)

endif
